atlanticwave-sdx/datamodel

- README.md
- test-requirements.txt
This PR addresses #27, and updates the documentation accordingly.
> Add `test-requirements.txt`

- .gitignore
- tests/data/sdx.json
- tests/test_topology_manager.py
A possible solution for #36.  But possibly also a wrong one, because I do not really understand the test suite yet.  Please review.
> Do not mutate test data

- .github/workflows/test.yml
Addresses #30.  This should run tests against a few Python 3.x versions.
[Here](https://github.com/sajith/datamodel/actions/runs/2504194631) is an example of this at work where the tests fail; [here](https://github.com/sajith/datamodel/actions/runs/2498094521) is an example were tests pass.
Tests are currently failing, so this PR will be in draft status until the cause of those failures are addressed.  Problem seems to be with `tests/data/sdx.json`: I removed that file in PR #28 because it keeps mutating during each test run. It is not a good idea for a file in version control to mutate like that. 
Perhaps that file should be two different files: (1) an input file that doesn't mutate, and (2) an output file that mutates, something which git can safely ignore.  I do not understand the test …
> Add a GitHub Actions configuration

- .github/workflows/test.yml
- setup.cfg
> Include all necessary modules when packaging

- .github/workflows/test.yml
> Report coverage status to coveralls.io

- .github/workflows/test.yml
- setup.cfg
> Add all modules 

- src/sdx/datamodel/parsing/connectionhandler.py
- tests/test_connection_handler.py
- tests/test_connection_validator.py
Issue is #48.  Both ConnectionHandler class and its tests have been refactored for simplicity.
> Refactor connection handler

- CHANGELOG.md
- setup.cfg
> Prepare datamodel for 2.0.0

- doc/requirements.txt
- schemas/Link.json
- schemas/Topology.json
- src/sdx_datamodel/data/topologies/amlight.json
- src/sdx_datamodel/data/topologies/sax.json
- src/sdx_datamodel/data/topologies/sdx.json
- src/sdx_datamodel/data/topologies/zaoxi.json
- src/sdx_datamodel/models/link.py
- src/sdx_datamodel/models/topology.py
- src/sdx_datamodel/parsing/linkhandler.py
- src/sdx_datamodel/parsing/topologyhandler.py
- src/sdx_datamodel/validation/topologyvalidator.py
This replaces time_stamp with timestamp (no underscore).
> Replace time_stamp with timestamp

- src/sdx_datamodel/parsing/porthandler.py
- src/sdx_datamodel/validation/connectionvalidator.py
- src/sdx_datamodel/validation/topologyvalidator.py
> Add logging

- pyproject.toml
- src/sdx_datamodel/models/link.py
- src/sdx_datamodel/models/location.py
- tests/test_link_handler.py
- tests/test_location_handler.py
Resolves #66, #67.  Also bumps up version, which is a step I missed in previous releases. :^)
> Simplify constructors

- schemas/Location.json
- src/sdx_datamodel/data/topologies/amlight.json
- src/sdx_datamodel/data/topologies/ampath.json
- src/sdx_datamodel/data/topologies/sax.json
- src/sdx_datamodel/data/topologies/sdx.json
- src/sdx_datamodel/data/topologies/zaoxi.json
- src/sdx_datamodel/models/location.py
- src/sdx_datamodel/parsing/locationhandler.py
- tests/data/location.json
- tests/data/node.json
- tests/test_location_handler.py
This PR adds "iso3166_2_lvl4" field to location object. This is required by Meican integration.
> Add iso3166_2_lvl4

- src/sdx_datamodel/data/topologies/amlight_link_failure.json
Add a sample topology request with link failure event.
> Add sample request with link failure

- src/sdx_datamodel/models/topology.py
- tests/test_topology.py
> add unitest for model.topology

- .github/workflows/checks.yml
- .github/workflows/test.yml
- .gitignore
- pyproject.toml
Changes:
- Use current versions of workflow steps
- Update black to current version
- Remove deprecated black configuration
- Ignore .venv directories
> Housekeeping updates

- src/sdx_datamodel/data/topologies/sax_v2.json
- src/sdx_datamodel/data/topologies/zaoxi_v2.json
- src/sdx_datamodel/parsing/servicehandler.py
- tests/test_service_handler.py
This pull request updates the data model files according to Topology Data Model Specification 2.0.0 (https://docs.google.com/document/d/1lgxjIT144EFu1G_OVcU19hN1cSUT_v2-tE0Z-7UlkNg/edit).
> Update datamodel topology files according to Spec 2.0.0

- pyproject.toml
- src/sdx_datamodel/data/requests/test-l2vpn-p2p-v2.json
- src/sdx_datamodel/data/requests/test-request-amlight_sax-p2p-v2.json
- tests/__init__.py
Added the test request json on this issue: when an endpoint is on a inter-domain link.
> 150 invalid v10 format connection request

- .github/workflows/test.yml
- pyproject.toml
- src/sdx_datamodel/models/link.py
- src/sdx_datamodel/models/node.py
- src/sdx_datamodel/models/topology.py
- tests/test_topology.py
added a method: Topology.get_link_by_port_id(self, port_id_0, port_id_1)
> 95 ports in links and nodes are dicts not port objects

- src/sdx_datamodel/data/requests/test-l2vpn-p2p-v2.json
- src/sdx_datamodel/data/topologies/amlight.json
- src/sdx_datamodel/data/topologies/amlight_link_failure.json
- src/sdx_datamodel/data/topologies/amlight_user_port.json
- src/sdx_datamodel/data/topologies/sax.json
- src/sdx_datamodel/data/topologies/sdx.json
- src/sdx_datamodel/data/topologies/zaoxi.json
fix a minor issue and close this old issue.
> fix a typo in a test request json

- pyproject.toml
- src/sdx_datamodel/models/topology.py
> version number

- pyproject.toml
- src/sdx_datamodel/data/requests/test_request-amlight_zaoxi-p2p-v2.json
- src/sdx_datamodel/data/requests/test_request.json
- src/sdx_datamodel/data/topologies/amlight.json
- src/sdx_datamodel/data/topologies/amlight_user_port.json
- src/sdx_datamodel/data/topologies/sax.json
- src/sdx_datamodel/data/topologies/sdx.json
- src/sdx_datamodel/data/topologies/zaoxi.json
Fix #182 
As presented on Issue #182, there are some inconsistencies on the topology data files in regards to the OXP domain name. This PR fixes those inconsistencies.
The CI pipeline has showed that unit tests were preserved passing.
I've also executed the unit tests on PCE using this branch:
```
collected 76 items
tests/test_path_function.py ✓✓✓                                                                                                                             4% ▌
tests/test_random_connection_generator.py ✓✓✓                                                                                                               8% ▊
tests/test_random_topology_generator.py ✓✓✓✓                                                                                                               13% …
```
> Fix topology data files to be consistent in regards to the OXP domain

- src/sdx_datamodel/constants.py
Add a constant, and a DB collection
> Add port connections dict
